
CREATE GENERATOR GEN_TABLEQUEUE_ID;

CREATE TABLE TABLEQUEUE (
    TABLEQUEUEID    DM_ID NOT NULL /* DM_ID = BIGINT */,
    CREDTM          DM_DATETIME /* DM_DATETIME = TIMESTAMP */,
    MSG             DM_BLOB /* DM_BLOB = BLOB SUB_TYPE BINARY SEGMENT SIZE 80 */,
    MSGORIGIN       DM_A100 /* DM_A100 = VARCHAR(100) */,
    MSGID           DM_A48 /* DM_A48 = VARCHAR(48) */,
    MSGNAME         DM_A255 /* DM_A255 = VARCHAR(255) */,
    MSGDESTINATION  DM_A100 /* DM_A100 = VARCHAR(100) */
);

ALTER TABLE TABLEQUEUE ADD CONSTRAINT PK_TABLEQUEUE PRIMARY KEY (TABLEQUEUEID);


SET TERM ^ ;

/* Trigger: TABLEQUEUE_BI */
CREATE OR ALTER TRIGGER TABLEQUEUE_BI FOR TABLEQUEUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.tablequeueid is null) then
    new.tablequeueid = gen_id(gen_tablequeue_id,1);
end
^
SET TERM ; ^

